version: '3.1'

services:

  drupal:
    image: drupal:8-apache
    ports:
      - 8888:80
    volumes:
      - modules:/var/www/html/modules
      - profiles:/var/www/html/profiles
      - themes:/var/www/html/themes
      - sites:/var/www/html/sites
    restart: always

  postgres:
    image: postgres:10
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always
volumes:
    modules: {}
    profiles: {}
    themes: {}
    sites: {}
    database: {}
